// <auto-generated />
using HostelFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HostelFinder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250508180736_initalcreate")]
    partial class initalcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HostelFinder.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("HostelFinder.Models.Hostel", b =>
                {
                    b.Property<string>("HostelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ADA")
                        .HasColumnType("int");

                    b.Property<int>("ADN")
                        .HasColumnType("int");

                    b.Property<int>("ASA")
                        .HasColumnType("int");

                    b.Property<int>("ASN")
                        .HasColumnType("int");

                    b.Property<int>("AvailableADA")
                        .HasColumnType("int");

                    b.Property<int>("AvailableADN")
                        .HasColumnType("int");

                    b.Property<int>("AvailableASA")
                        .HasColumnType("int");

                    b.Property<int>("AvailableASN")
                        .HasColumnType("int");

                    b.Property<int>("AvailableNDA")
                        .HasColumnType("int");

                    b.Property<int>("AvailableNDN")
                        .HasColumnType("int");

                    b.Property<int>("AvailableNSA")
                        .HasColumnType("int");

                    b.Property<int>("AvailableNSN")
                        .HasColumnType("int");

                    b.Property<string>("HostelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NDA")
                        .HasColumnType("int");

                    b.Property<int>("NDN")
                        .HasColumnType("int");

                    b.Property<int>("NSA")
                        .HasColumnType("int");

                    b.Property<int>("NSN")
                        .HasColumnType("int");

                    b.HasKey("HostelId");

                    b.ToTable("Hostels");
                });

            modelBuilder.Entity("HostelFinder.Models.Student", b =>
                {
                    b.Property<int>("MobileNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MobileNumber"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachingInstitute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HostelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreparationFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatPreferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tehsil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MobileNumber");

                    b.HasIndex("HostelId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HostelFinder.Models.Student", b =>
                {
                    b.HasOne("HostelFinder.Models.Hostel", "Hostel")
                        .WithMany("Students")
                        .HasForeignKey("HostelId");

                    b.Navigation("Hostel");
                });

            modelBuilder.Entity("HostelFinder.Models.Hostel", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
