// <auto-generated />
using HostelFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HostelFinder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HostelFinder.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("HostelFinder.Models.Hostel", b =>
                {
                    b.Property<string>("HostelId")
                        .HasColumnType("text");

                    b.Property<int>("ADA")
                        .HasColumnType("integer");

                    b.Property<int>("ADAPRICE")
                        .HasColumnType("integer");

                    b.Property<int>("ADN")
                        .HasColumnType("integer");

                    b.Property<int>("ADNPRICE")
                        .HasColumnType("integer");

                    b.Property<int>("ASA")
                        .HasColumnType("integer");

                    b.Property<int>("ASAPRICE")
                        .HasColumnType("integer");

                    b.Property<int>("ASN")
                        .HasColumnType("integer");

                    b.Property<int>("ASNPRICE")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableADA")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableADN")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableASA")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableASN")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableNDA")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableNDN")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableNSA")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableNSN")
                        .HasColumnType("integer");

                    b.Property<string>("HostelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NDA")
                        .HasColumnType("integer");

                    b.Property<int>("NDAPRICE")
                        .HasColumnType("integer");

                    b.Property<int>("NDN")
                        .HasColumnType("integer");

                    b.Property<int>("NDNPRICE")
                        .HasColumnType("integer");

                    b.Property<int>("NSA")
                        .HasColumnType("integer");

                    b.Property<int>("NSAPRICE")
                        .HasColumnType("integer");

                    b.Property<int>("NSN")
                        .HasColumnType("integer");

                    b.Property<int>("NSNPRICE")
                        .HasColumnType("integer");

                    b.HasKey("HostelId");

                    b.ToTable("Hostels");
                });

            modelBuilder.Entity("HostelFinder.Models.Student", b =>
                {
                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoachingInstitute")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostelId")
                        .HasColumnType("text");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Money")
                        .HasColumnType("text");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreparationFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatPreferenceCode")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tehsil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MobileNumber");

                    b.HasIndex("HostelId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HostelFinder.Models.Student", b =>
                {
                    b.HasOne("HostelFinder.Models.Hostel", "Hostel")
                        .WithMany("Students")
                        .HasForeignKey("HostelId");

                    b.Navigation("Hostel");
                });

            modelBuilder.Entity("HostelFinder.Models.Hostel", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
